# Generated by Django 4.2.2 on 2023-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_reel_transactions_reel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel_transactions',
            name='reel_no',
            field=models.IntegerField(null=True),
        ),
    ]
